[package]
name = "fake-virus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-dialog = "0.6.3"
dirs = "4.0.0"
machine-uid = "0.2.0"
sha256 = "1.0.3"
#whoami = "1.2.1"
